import { MenuCategory } from "./types";

export const menuCategories: MenuCategory[] = [
  {
    id: "combos",
    label: "Combos",
    image: "/1.png",
    items: [
      {
        id: "quick-feed",
        name: "QUICK FEED",
        image: "/Item-1/1.png",
        price: 12,
        isVeg: true,
        description: "A quick single burger, fries and a drink — perfect for an on-the-go bite.",
        macros: { cals: 650, carbs: 70, protein: 25 },
      },
      {
        id: "the-loot-box",
        name: "THE LOOT BOX",
        image: "/Item-1/2.png",
        price: 11,
        isVeg: false,
        description: "A hearty mix of burger, nuggets and fries bundled into one loaded box.",
        macros: { cals: 780, carbs: 82, protein: 32 },
      },
      {
        id: "family-feast",
        name: "FAMILY FEAST",
        image: "/Item-1/3.png",
        price: 28,
        isVeg: true,
        description: "Four burgers, sides and drinks — built to feed the whole family.",
        macros: { cals: 2400, carbs: 210, protein: 95 },
      },
      {
        id: "orchard-special",
        name: "ORCHARD SPECIAL",
        image: "/Item-1/4.png",
        price: 19,
        isVeg: true,
        description: "Our signature burger paired with crispy fries and a refreshing drink.",
        macros: { cals: 890, carbs: 88, protein: 36 },
      },
      {
        id: "classic-treo",
        name: "CLASSIC TREO",
        image: "/Item-1/5.png",
        price: 8,
        isVeg: false,
        description: "The essential trio — burger, fries and a drink at a great price.",
        macros: { cals: 620, carbs: 64, protein: 24 },
      },
      {
        id: "treasure-box",
        name: "TREASURE BOX",
        image: "/Item-1/6.png",
        price: 35,
        isVeg: false,
        description: "A generous spread of burgers, wings and sides for sharing.",
        macros: { cals: 3100, carbs: 260, protein: 120 },
      },
    ],
  },
  {
    id: "signature-range",
    label: "Signature Range",
    image: "/22.png",
    items: [
      {
        id: "sig-margherita",
        name: "Signature Margherita",
        image: "/Item-2/1.png",
        price: 18,
        isVeg: true,
        description: "Fresh mozzarella, vine tomatoes and basil on our signature base.",
        macros: { cals: 620, carbs: 78, protein: 24 },
      },
      {
        id: "sig-pepperoni-supreme",
        name: "Signature Pepperoni Supreme",
        image: "/Item-2/2.png",
        price: 22,
        isVeg: false,
        description: "Double pepperoni layered over melted mozzarella and signature sauce.",
        macros: { cals: 780, carbs: 74, protein: 34 },
      },
      {
        id: "sig-bbq-chicken",
        name: "Signature BBQ Chicken",
        image: "/Item-2/3.png",
        price: 23,
        isVeg: false,
        description: "Smoky barbecue chicken, red onions and mozzarella on a tangy BBQ base.",
        macros: { cals: 710, carbs: 76, protein: 38 },
      },
      {
        id: "sig-farmhouse",
        name: "Signature Farmhouse",
        image: "/Item-2/4.png",
        price: 20,
        isVeg: true,
        description: "A garden mix of bell peppers, onions, mushrooms and sweetcorn.",
        macros: { cals: 640, carbs: 80, protein: 22 },
      },
      {
        id: "sig-peri-peri-paneer",
        name: "Signature Peri Peri Paneer",
        image: "/Item-2/5.png",
        price: 21,
        isVeg: true,
        description: "Fiery peri peri paneer cubes with onions and peppers on melted cheese.",
        macros: { cals: 660, carbs: 72, protein: 28 },
      },
      {
        id: "sig-meat-lovers",
        name: "Signature Meat Lovers",
        image: "/Item-2/6.png",
        price: 25,
        isVeg: false,
        description: "Pepperoni, chicken and beef piled high for the ultimate meat feast.",
        macros: { cals: 860, carbs: 70, protein: 44 },
      },
    ],
  },
  {
    id: "gourmet-pizza",
    label: "Gourmet Pizza",
    image: "/3.png",
    items: [
      {
        id: "the-orchard-special",
        name: "THE ORCHARD SPECIAL",
        image: "/Item-3/1.png",
        price: 24,
        isVeg: true,
        description: "Wood-fired gourmet pizza topped with seasonal roasted vegetables and herbs.",
        macros: { cals: 680, carbs: 78, protein: 22 },
      },
      {
        id: "gourmet-prosciutto-arugula",
        name: "PROSCIUTTO & ARUGULA",
        image: "/Item-3/2.png",
        price: 26,
        isVeg: false,
        description: "Thin-cut prosciutto, peppery arugula and shaved parmesan.",
        macros: { cals: 720, carbs: 68, protein: 32 },
      },
      {
        id: "gourmet-four-cheese",
        name: "FOUR CHEESE GOURMET PIZZA",
        image: "/Item-3/3.png",
        price: 23,
        isVeg: true,
        description: "A rich blend of mozzarella, gorgonzola, parmesan and ricotta.",
        macros: { cals: 760, carbs: 70, protein: 34 },
      },
      {
        id: "gourmet-smoked-salmon",
        name: "SMOKED SALMON GOURMET PIZZA",
        image: "/Item-3/4.png",
        price: 27,
        isVeg: false,
        description: "Delicate smoked salmon, cream cheese and dill over a crisp base.",
        macros: { cals: 700, carbs: 66, protein: 30 },
      },
    ],
  },
  {
    id: "bollywood-flavours",
    label: "Bollywood Flavours",
    image: "/5.png",
    items: [
      {
        id: "chicken-chatkara",
        name: "CHICKEN CHATKARA",
        image: "/Item-5/1.png",
        price: 17,
        isVeg: false,
        description: "Spiced chicken tikka pieces with a tangy, chatpata masala kick.",
        macros: { cals: 420, carbs: 32, protein: 30 },
      },
      {
        id: "chilli-paneer",
        name: "CHILLI PANEER",
        image: "/Item-5/2.png",
        price: 18,
        isVeg: true,
        description: "Crispy paneer tossed in a spicy Indo-Chinese chilli sauce.",
        macros: { cals: 380, carbs: 34, protein: 18 },
      },
      {
        id: "paneer-tikka",
        name: "PANEER TIKKA",
        image: "/Item-5/3.png",
        price: 15,
        isVeg: true,
        description: "Smoky char-grilled paneer marinated in classic tikka spices.",
        macros: { cals: 360, carbs: 28, protein: 20 },
      },
      {
        id: "peri-peri-paneer",
        name: "PERI PERI PANEER",
        image: "/Item-5/4.png",
        price: 16,
        isVeg: true,
        description: "Fiery peri peri spiced paneer, grilled and packed with flavour.",
        macros: { cals: 370, carbs: 26, protein: 19 },
      },
      {
        id: "paneer-chatkara",
        name: "PANEER CHATKARA",
        image: "/Item-5/5.png",
        price: 18,
        isVeg: true,
        description: "Bold, chatpata spiced paneer bursting with Indian street-food flavour.",
        macros: { cals: 390, carbs: 30, protein: 20 },
      },
      {
        id: "butter-paneer",
        name: "BUTTER PANEER",
        image: "/Item-5/1.png",
        price: 17,
        isVeg: true,
        description: "Soft paneer simmered in a rich, buttery tomato gravy.",
        macros: { cals: 410, carbs: 32, protein: 18 },
      },
    ],
  },
  {
    id: "gourmet-burgers",
    label: "Gourmet Burgers",
    image: "/7.png",
    items: [
      {
        id: "the-bulldozer-burger",
        name: "The Bulldozer Burger",
        image: "/Item-4/1.png",
        price: 16,
        isVeg: false,
        description:
          "An all time BBQ favourite — beef patty, onions and herbs, topped with cheese, lettuce and tomato.",
        macros: { cals: 472, carbs: 38, protein: 26 },
      },
      {
        id: "big-hen",
        name: "Big Hen",
        image: "/Item-4/2.png",
        price: 18,
        isVeg: false,
        description: "Two beef patties, double cheese, and a toasted sesame bun.",
        macros: { cals: 326, carbs: 42, protein: 28 },
      },
      {
        id: "the-fat-kiwi",
        name: "The Fat Kiwi",
        image: "/Item-4/3.png",
        price: 20,
        isVeg: true,
        description: "Vegetarian patty loaded with fresh greens, tomato and onion.",
        macros: { cals: 218, carbs: 30, protein: 12 },
      },
      {
        id: "the-orchard-king",
        name: "The Orchard King",
        image: "/Item-4/1.png",
        price: 22,
        isVeg: false,
        description: "Chargrilled patty with a spiced chili glaze, barbecue-style.",
        macros: { cals: 280, carbs: 33, protein: 24 },
      },
      {
        id: "veggie-burger",
        name: "Veggie Burger",
        image: "/Item-4/2.png",
        price: 14,
        isVeg: true,
        description: "Lighter build with a toasted bun and fresh crunchy veg.",
        macros: { cals: 312, carbs: 29, protein: 14 },
      },
      {
        id: "smoky-bbq-burger",
        name: "Smoky BBQ Burger",
        image: "/Item-4/3.png",
        price: 19,
        isVeg: false,
        description: "Smoky barbecue sauce, crispy onions, melted cheddar.",
        macros: { cals: 340, carbs: 36, protein: 27 },
      },
    ],
  },
  {
    id: "ribs",
    label: "Ribs",
    image: "/8.png",
    items: [
      {
        id: "ribs-half-rack-bbq",
        name: "Half Rack BBQ Ribs",
        image: "/Item-6/1.png",
        price: 26,
        isVeg: false,
        description: "Slow-cooked pork ribs glazed in smoky house barbecue sauce.",
        macros: { cals: 890, carbs: 42, protein: 58 },
      },
      {
        id: "ribs-half-rack-bbq-combo",
        name: "Half Rack BBQ Ribs Combo",
        image: "/Item-6/2.png",
        price: 20,
        isVeg: false,
        description: "Half rack BBQ ribs served with fries and a drink.",
        macros: { cals: 1150, carbs: 78, protein: 62 },
      },
    ],
  },
  {
    id: "wings",
    label: "Wings",
    image: "/9.png",
    items: [
      {
        id: "wings-peri-peri-chicken",
        name: "Peri Peri Chicken Wings",
        image: "/Item-7/1.png",
        price: 14,
        isVeg: false,
        description: "Crispy chicken wings tossed in fiery peri peri seasoning.",
        macros: { cals: 480, carbs: 18, protein: 32 },
      },
      {
        id: "wings-peri-peri",
        name: "Peri Peri Wings",
        image: "/Item-7/2.png",
        price: 15,
        isVeg: false,
        description: "Classic wings glazed with our signature peri peri sauce.",
        macros: { cals: 460, carbs: 16, protein: 30 },
      },
      {
        id: "wings-butter-chicken",
        name: "Butter Chicken Wings",
        image: "/Item-7/3.png",
        price: 15,
        isVeg: false,
        description: "Crispy wings coated in a rich, creamy butter chicken glaze.",
        macros: { cals: 500, carbs: 20, protein: 31 },
      },
    ],
  },
  {
    id: "drinks",
    label: "Drinks",
    image: "/10.png",
    items: [
      {
        id: "sprite",
        name: "Sprite",
        image: "/Item-9/1.png",
        price: 5,
        isVeg: true,
        macros: { cals: 90, carbs: 22, protein: 0 },
      },
      {
        id: "Coca-Cola",
        name: "Coca-Cola",
        image: "/Item-9/2.png",
        price: 4,
        isVeg: true,
        macros: { cals: 60, carbs: 15, protein: 0 },
      },
    ],
  },
  {
    id: "shakes",
    label: "Shakes",
    image: "/11.png",
    items: [
      {
        id: "shake-chocolate",
        name: "Chocolate Shake",
        image: "/Item-8/1.png",
        price: 6,
        isVeg: true,
        description: "Thick and creamy shake blended with rich chocolate.",
        macros: { cals: 420, carbs: 62, protein: 8 },
      },
      {
        id: "shake-strawberry",
        name: "Strawberry Shake",
        image: "/Item-8/2.png",
        price: 6,
        isVeg: true,
        description: "Creamy shake blended with fresh strawberry flavour.",
        macros: { cals: 380, carbs: 58, protein: 7 },
      },
      {
        id: "shake-caramel",
        name: "Caramel Shake",
        image: "/Item-8/4.png",
        price: 6,
        isVeg: true,
        description: "Smooth shake swirled with sweet, buttery caramel.",
        macros: { cals: 440, carbs: 64, protein: 8 },
      },
      {
        id: "shake-mango",
        name: "Mango Shake",
        image: "/Item-8/3.png",
        price: 7,
        isVeg: true,
        description: "Refreshing shake blended with ripe, tropical mango.",
        macros: { cals: 360, carbs: 60, protein: 6 },
      },
      {
        id: "shake-vanilla",
        name: "Vanilla Shake",
        image: "/Item-8/5.png",
        price: 7,
        isVeg: true,
        description: "Classic creamy shake with smooth vanilla flavour.",
        macros: { cals: 400, carbs: 56, protein: 8 },
      },
    ],
  },
  {
    id: "desserts",
    label: "Desserts",
    image: "/12.png",
    items: [
      {
        id: "dessert-brownie",
        name: "Brownie",
        image: "/Item-10/1.png",
        price: 7,
        isVeg: true,
        description: "A rich, fudgy chocolate brownie baked in-house.",
        macros: { cals: 350, carbs: 46, protein: 5 },
      },
      {
        id: "dessert-choco-lava-cake",
        name: "Chocolate Lava Cake",
        image: "/Item-10/2.png",
        price: 7,
        isVeg: true,
        description: "Warm chocolate cake with a molten, gooey centre.",
        macros: { cals: 420, carbs: 52, protein: 6 },
      },
      {
        id: "dessert-chocolate-mousse",
        name: "Chocolate Mousse",
        image: "/Item-10/3.png",
        price: 8,
        isVeg: true,
        description: "Light and airy chocolate mousse, chilled and silky smooth.",
        macros: { cals: 320, carbs: 34, protein: 5 },
      },
    ],
  },
];